kubernetes/apps/rook-ceph/kustomization.yaml
kubernetes/apps/rook-ceph/namespace.yaml
kubernetes/apps/rook-ceph/rook-ceph/app/helmrelease.yaml
kubernetes/apps/rook-ceph/rook-ceph/app/kustomization.yaml
kubernetes/apps/rook-ceph/rook-ceph/cluster/helmrelease.yaml
kubernetes/apps/rook-ceph/rook-ceph/cluster/kustomization.yaml
kubernetes/apps/rook-ceph/rook-ceph/ks.yaml

First attempt at installing a rook-ceph cluster

initial rook-ceph commit

---

kubernetes/apps/monitoring/kubernetes-dashboard/app/helmrelease.yaml

Revert "feat(helm)!: Update chart kubernetes-dashboard to 7.0.2"

---

kubernetes/apps/monitoring/kubernetes-dashboard/app/helmrelease.yaml

Revert "feat(helm)!: Update chart kubernetes-dashboard to 7.0.2 - autoclosed"

---

README.md
bootstrap/tasks/addons/discord_template_notifier.yaml
bootstrap/tasks/addons/main.yaml
bootstrap/templates/addons/discord-template-notifier/app/helmrelease.yaml.j2
bootstrap/templates/addons/discord-template-notifier/app/kustomization.yaml.j2
bootstrap/templates/addons/discord-template-notifier/app/secret.sops.yaml.j2
bootstrap/templates/addons/discord-template-notifier/ks.yaml.j2
bootstrap/templates/kubernetes/apps/default/kustomization.yaml.j2
bootstrap/templates/kubernetes/apps/networking/cloudflared/app/configs/config.yaml.j2
bootstrap/templates/kubernetes/apps/networking/nginx/external/helmrelease.yaml.j2
bootstrap/vars/addons.sample.yaml
bootstrap/vars/config.sample.yaml

Merge cherry-picked changes from template

Chore: keep up to date with template

---

.gitignore
infrastructure/terraform/cloudflare/.terraform.lock.hcl
infrastructure/terraform/cloudflare/account.tf
infrastructure/terraform/cloudflare/domain.tf
infrastructure/terraform/cloudflare/locals.tf
infrastructure/terraform/cloudflare/main.tf
infrastructure/terraform/cloudflare/modules/cf_domain/dns.tf
infrastructure/terraform/cloudflare/modules/cf_domain/main.tf
infrastructure/terraform/cloudflare/modules/cf_domain/outputs.tf
infrastructure/terraform/cloudflare/modules/cf_domain/variables.tf
infrastructure/terraform/cloudflare/modules/cf_domain/waf.tf
infrastructure/terraform/cloudflare/providers.tf

This pull request includes updates to the Cloudflare configuration. The following changes have been made:
- Updated the .gitignore and main.tf files
- Updated the Cloudflare vault in main.tf
- Updated the Cloudflare provider credentials
- Yoinked the cf_domain module
- Updated the Cloudflare account name and added domain configuration
- Updated the Cloudflare account and domain configurations
- Added DMARC and WAF custom rule for GitHub flux API

Update Cloudflare configuration

---

kubernetes/apps/default/immich/app/machine-learning/helmrelease.yaml
kubernetes/apps/default/immich/app/microservices/helmrelease.yaml
kubernetes/apps/default/immich/app/server/helmrelease.yaml

Revert "feat(container): update immich group to v1.89.0 (minor)"

---

kubernetes/main/apps/default/immich/app/machine-learning/helmrelease.yaml
kubernetes/main/apps/default/immich/app/microservices/helmrelease.yaml
kubernetes/main/apps/default/immich/app/server/helmrelease.yaml

Revert "feat(container): update immich group to v1.91.2 (minor)"

---

kubernetes/main/apps/media/qbittorrent/app/qbittools-tagging/helmrelease.yaml

Revert "feat(container): update ghcr.io/buroa/qbtools ( v0.11.0 → v0.13.0 )"

---

kubernetes/main/apps/actions-runner-system/actions-runner-controller/runners/helmrelease.yaml

Revert "chore(deps): update image gha-runner-scale-set to v0.8.2"

---

kubernetes/main/apps/actions-runner-system/actions-runner-controller/app/helmrelease.yaml

Revert "chore(deps): update image gha-runner-scale-set-controller to v0.8.2"

---

kubernetes/main/apps/selfhosted/immich/app/machine-learning/helmrelease.yaml
kubernetes/main/apps/selfhosted/immich/app/microservices/helmrelease.yaml
kubernetes/main/apps/selfhosted/immich/app/server/helmrelease.yaml

Revert "chore(deps): update immich group to v1.95.1 (minor)"

---

kubernetes/main/apps/selfhosted/immich/app/machine-learning/helmrelease.yaml
kubernetes/main/apps/selfhosted/immich/app/microservices/helmrelease.yaml
kubernetes/main/apps/selfhosted/immich/app/server/helmrelease.yaml

Revert "Revert "chore(deps): update immich group to v1.95.1 (minor)""

---

kubernetes/main/apps/selfhosted/immich/app/machine-learning/helmrelease.yaml
kubernetes/main/apps/selfhosted/immich/app/microservices/helmrelease.yaml
kubernetes/main/apps/selfhosted/immich/app/server/helmrelease.yaml

Revert "Revert "Revert "chore(deps): update immich group to v1.95.1 (minor)"""

---

kubernetes/main/apps/kubevirt/kubevirt/ks.yaml
kubernetes/main/apps/kubevirt/kustomization.yaml
kubernetes/main/apps/kubevirt/namespace.yaml
kubernetes/main/apps/kubevirt/notifications.yaml
kubernetes/main/flux/repositories/git/kubevirt-cdi.yaml
kubernetes/main/flux/repositories/git/kubevirt.yaml
kubernetes/main/flux/repositories/git/kustomization.yaml

This pull request adds the kubevirt and kubevirt-cdi resources to the repository.

feat: Add kubevirt and kubevirt-cdi resources

---

kubernetes/main/apps/security/zitadel/app/helmrelease.yaml

Revert "chore(deps): update image ghcr.io/zitadel/zitadel to v2.48.1"

---

kubernetes/main/apps/actions-runner-system/actions-runner-controller/app/helmrelease.yaml
kubernetes/main/apps/actions-runner-system/actions-runner-controller/runners/helmrelease.yaml

Revert "chore(deps): update actions runner controller group to v0.9.0 (minor)"

---

kubernetes/main/apps/system/volsync/app/helmrelease.yaml

Revert "chore(deps): update volsync group to v0.9.1 (patch)"

---

kubernetes/main/apps/system/reloader/app/helmrelease.yaml

Revert "chore(deps): update chart reloader to v1.0.86"

---

kubernetes/main/apps/media/kyoo/app/helmrelease.yaml

Revert "chore(deps): update image docker.io/getmeili/meilisearch to v1.7"

---

kubernetes/main/apps/selfhosted/vikunja/app/helmrelease.yaml

Revert "fix(container): update caddy ( 2.8.0 → 2.8.1 )"

---

kubernetes/main/flux/config/flux.yaml

Revert "chore(deps): pin image ghcr.io/fluxcd/flux-manifests to 5870003"

---

kubernetes/main/apps/observability/loki/app/helmrelease.yaml

Revert "fix(helm): update loki (6.7.1 → 6.7.2)"

---

kubernetes/main/apps/networking/multus/app/helmrelease.yaml

Revert "feat(container): update ghcr.io/k8snetworkplumbingwg/multus-cni (v4.0.2 → v4.1.0)"

---

kubernetes/main/apps/networking/external-dns/cloudflare/helmrelease.yaml
kubernetes/main/apps/networking/external-dns/unifi/helmrelease.yaml

Revert "feat(helm): update external-dns (1.14.5 → 1.15.0)"

---

kubernetes/main/apps/media/pinepods/app/helmrelease.yaml

Revert "fix(container): update madeofpendletonwool/pinepods (0.6.5 → 0.6.6)"

---

kubernetes/main/apps/media/qbittorrent/app/helmrelease.yaml

Revert "feat(container)!: Update ghcr.io/onedr0p/qbittorrent (4.6.7 → 5.0.0)"

---

kubernetes/main/apps/system-upgrade/kustomization.yaml
kubernetes/main/apps/system-upgrade/namespace.yaml
kubernetes/main/apps/system-upgrade/system-upgrade-controller/app/helmrelease.yaml
kubernetes/main/apps/system-upgrade/system-upgrade-controller/app/kustomization.yaml
kubernetes/main/apps/system-upgrade/system-upgrade-controller/app/rbac.yaml
kubernetes/main/apps/system-upgrade/system-upgrade-controller/ks.yaml
kubernetes/main/apps/system-upgrade/system-upgrade-controller/plans/kubernetes.yaml
kubernetes/main/apps/system-upgrade/system-upgrade-controller/plans/kustomization.yaml
kubernetes/main/apps/system-upgrade/system-upgrade-controller/plans/talos-control.yaml
kubernetes/main/apps/system-upgrade/system-upgrade-controller/plans/talos-worker.yaml

Attempt yoinking system-upgrade with dedicated plans for control plane and worker nodes with different talos schematic IDs

feat: deploy system-upgrade-controller

---

kubernetes/main/apps/selfhosted/home-assistant/app/helmrelease.yaml

Revert "feat(container): update ghcr.io/onedr0p/home-assistant (2024.11.3 → 2024.12.1)"

---

kubernetes/apps/selfhosted/hoarder/app/helmrelease.yaml

Revert "feat(container): update ghcr.io/hoarder-app/hoarder ( 0.21.0 → 0.22.0 )"

---

kubernetes/apps/selfhosted/atuin/app/externalsecret.yaml
kubernetes/apps/selfhosted/atuin/app/helmrelease.yaml
kubernetes/apps/selfhosted/atuin/app/kustomization.yaml
kubernetes/apps/selfhosted/atuin/ks.yaml

Revert "feat: Move atuin to sqlite home-operations container"

---

kubernetes/apps/selfhosted/karakeep/app/helmrelease.yaml

Revert "fix(container): update image docker.io/getmeili/meilisearch ( v1.17.0 → v1.17.1 )"
